apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mydep1
  name: mydep1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mydep1
  type: NodePort
status:
  loadBalancer: {}
